name: "Verify MCP Usage"
description: "Verifies that both CloudWatch and Application Signals MCP tools were called"

inputs:
  artifact_name:
    description: "Name of the artifact containing test outputs"
    required: true
  output_path:
    description: "Path to download test outputs"
    required: false
    default: "./test-outputs"

runs:
  using: "composite"
  steps:
    - name: Download test outputs
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ inputs.output_path }}

    - name: Verify MCP tool usage
      shell: bash
      run: |
        echo "Checking for MCP tool usage..."
        
        RAW_OUTPUT_FILE="${{ inputs.output_path }}/awsapm-raw-output.txt"
        
        if [[ ! -f "$RAW_OUTPUT_FILE" ]]; then
          echo "ERROR: Raw output file not found"
          exit 1
        fi
        
        # Check for both MCP tool calls
        if grep -qE "Using tool: list_monitored_services.*from mcp server.*awslabs\.cloudwatch-appsignals-mcp" "$RAW_OUTPUT_FILE"; then
          echo "PASSED - list_monitored_services tool was called from AWS Application Signals MCP"
        else
          echo "FAILED: list_monitored_services tool call not found"
          echo "Raw output content:"
          cat "$RAW_OUTPUT_FILE"
          exit 1
        fi
        
        if grep -qE "Using tool: get_active_alarms.*from mcp server.*awslabs\.cloudwatch-mcp" "$RAW_OUTPUT_FILE"; then
          echo "PASSED - get_active_alarms tool was called from CloudWatch MCP"
        else
          echo "FAILED: get_active_alarms tool call not found"
          echo "Raw output content:"
          cat "$RAW_OUTPUT_FILE"
          exit 1
        fi